# Enable dynamic background opacity
dynamic_background_opacity yes
background_opacity 0.9
background_blur 5

# Kanagawa theme
cursor #c8c093
cursor_text_color #1f1f28
foreground #dcd7ba
background #1f1f28
selection_foreground #dcd7ba
selection_background #2d2d3d
color0 #16161d
color8 #54546d
color1 #c34043
color9 #e82424
color2 #76946a
color10 #98bb6c
color3 #c0a36e
color11 #dca561
color4 #7e9cd8
color12 #7fb4ca
color5 #957fb8
color13 #938aa9
color6 #6a9589
color14 #7aa89f
color7 #c8c093
color15 #dcd7ba
url_color #7fb4ca
active_border_color #7e9cd8
inactive_border_color #54546d
bell_border_color #c0a36e
# END_THEME

font_family      JetBrainsMono Nerd Font
bold_font         JetBrainsMono Nerd Font Bold
italic_font       JetBrainsMono Nerd Font Italic
bold_italic_font  JetBrainsMono Nerd Font Bold Italic
font_size 10.0