-- Auto-generated by theme switcher. Do not edit.
vim.g.theme = "kanagawa"
vim.cmd("colorscheme kanagawa")
-- Re-apply after lazy fully loads, in case another plugin overrides
vim.api.nvim_create_autocmd("User", {
  pattern = "LazyDone",
  callback = function()
    vim.cmd("colorscheme kanagawa")
  end,
})
